### ISSUE TITLE
Allow use of different 'folder' name

### ISSUE THREAD

**Issue by mclarkson** [maestrx/nagrestconf-python#1]
Hi,
The default 'folder' name of 'local' is good, since that is common for single instances, but for multi-instance nagios the folder name will not be 'local'. Can this be an option?

Cheers!
Mark.

**Comment by maestrx** [comment]
Hi,

Updated vestion commited to github. Use –F option.

Still thinking about the  URL encode form previoous email. In my view the current implementation is correct, its just that in your usecase you are having the input data in the url-encoded form. So do I understand that you could either do the url-decoding yourself and pass the data in the “cleartext” form or you would need to have some extra feature in the tool to do the urldecode prior accepting the input data?

BR

Vit

**Comment by mclarkson** [comment]
'-F' option works for me, thanks :)

I'll open individual issues for the other items.
