### ISSUE TITLE
Allow non-urlencoded plain text in queries

### ISSUE THREAD

**Issue by mclarkson** [maestrx/nagrestconf-python#2]
In the nagrestconf GUI all items are shown in their decoded form, and the user is not expected to enter url encoded data. It would be great if this tool was the same. For example:

I look in the nagrestconf GUI and see 'Processes: Zombies'.
I want to see 'Processes: Zombies' with nagrestconf-python so I try a nagrestconf-python filter:

```
./nagrestconf.py -s $URL -r show/services -f 'svcdesc:Processes: Zombies'
```

Which does not work. Next I try a nagrestconf filter:

```
./nagrestconf.py -s $URL -r show/services -d 'filter:Processes: Zombies,column:4'
```

Which also doesn't work.

To make the above work I have to change ': ' to '%3A+', which is not natural or intuitive.

Can nagrestconf-python be made to allow non-urlencoded data as above?

**Comment by maestrx** [comment]
Fixed by fixing #3
