### ISSUE TITLE
no LICENSE

### ISSUE THREAD

**Issue by poinck** [maestrx/nagrestconf-python#4]
I want to use this in a project (and package it for CentOS 7), but without LICENSE-information, I cannot do this.

Btw., great work.

**Comment by maestrx** [comment]
I dont care about license and dont understand it. How and what license should I assign?

**Comment by poinck** [comment]
I know the feeling. ^^ I use CC0 in most cases. I wish it would not be necessary to declare how software can be used.

I see, you have already choosen GPLv3. This license makes it possible for me to use your work safely. I do not plan to change it, so I will not have any issues with copy-left.
